# Generated by Django 5.0.2 on 2025-12-04 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0004_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='publico_objetivo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
